name: Deploy Automatico ReplayLead

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixando código do GitHub
        uses: actions/checkout@v4

      - name: 2. Conectando e Atualizando Servidor
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Iniciando atualizacao do ReplayLead..."
            cd /var/www/replay-lead-crm
            bash ./atualizar-replaylead.sh
            echo "Deploy concluido."
